#!/usr/bin/env bash


# TODO add list.txt for apps that is needed to move or use a git repo that only contain those config

# Setup
# repo
note_url="https://github.com/sokinpui/note"
blog_url="https://github.com/sokinpui/blog-sokinpui"
vim_url="https://github.com/sokinpui/vim"
config_url="https://github.com/sokinpui/fedora-gnome-config"
kmonad_url="https://github.com/kmonad/kmonad.git"

# script
z_url="https://raw.githubusercontent.com/agkozak/zsh-z/master/zsh-z.plugin.zsh"
git_prompt="https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"

mkdir -p $HOME/git_repo/mine
mkdir -p $HOME/git_repo/mine


# cloning repo into local machine
git clone $note_url $HOME/git_repo/mine/note
git clone $blog_url $HOME/git_repo/mine/blog
git clone $vim_url $HOME/.vim
git clone $config_url $HOME/merged_config
git clone $kmonad_url $HOME/git_repo/kmonad

# install zsh-z and git_prompt script
wget --directory-prefix $HOME/.local $z_url
wget --directory-prefix $HOME/.local $git_prompt

# merge the config into local machine from list.txt
names=$(cat list.txt)

for name in $names; do
  mv $HOME/merged_config/$name $HOME/.config
done

ln -s $HOME/.config/zsh/env $HOME/.zshenv
ln -s $HOME/.config/zsh/profile $HOME/.zprofile


# install necessary packages
sudo dnf install -y \
  vim gvim neovim \
  alacritty \
  zsh \
  tmux \
  htop \
  stack \
  neofetch \
  newsboat \
  jetbrains-mono-fonts-all.noarch \
  hugo \
  gnome-tweaks \
  fd-find \
  ripgrep \
  flatpak \
  fzf \
  pandoc \
  fcitx5* fcitx5-chinese-addons \
  steam wqy-zenhei-font \
  julia \
  https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm \
  ffmpeg-libs gstreamer1-plugin-openh264 mozilla-openh264 \
  gh

sudo dnf config-manager --set-enabled fedora-cisco-openh264

# TODO gnome-shell-extension

# complie kmonad
cd $HOME/git_repo/kmonad

stack build

exce_binary=$(find $HOME/git_repo/kmonad | grep "/bin/kmonad")
sudo cp $exce_binary /usr/local/bin/kmonad
sudo chmod +x /usr/local/bin/kmonad

cd $HOME

# TODO apps that is installed using software.
# install GUI application via flatpak
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

flatpak install flathub md.obsidian.Obsidian



# remove the cloned config repo from old machine
rm -rf $HOME/merged_config

# change ibus to fcitx5
fcitx5-config-qt
