#!usr/bin/env bash

restart_shell() {
  clear && echo "restart shell"
  exec $SHELL
}

# change directory with fzf, $1 is parent dir of the target.
cdf() {
  [ -z "$1" ] && echo "Usage: change directory with fancy find. cdf <dir>"
  # TODO support options
  cd $(find $1 | fzf)
}

mkdc () { mkdir -p "$@" && eval cd "\"\$$#\""; }

ed() { command ed -p\> "$@" ; }

# $1 numbers of files going to be moved, $2 target directory
move_recent_download_to_dir() {
  dfiles=$( ls -td ~/Downloads/* | head -n $1)
  mv $dfiles $2
}

# CSE gateway
gw() {
  echo "usage: connect to CSE gateway."
  echo "After connection, use ssh linux[1-16] to connect remote machine."
  ssh kpso2@gw.cse.cuhk.edu.hk
}

# quick editing
alias \
  vim="nvim" \
  viM="nvim" \
  vIM="nvim" \
  vIm="nvim" \
  vi="nvim" \
  vI="nvim" \
  v="nvim" \
  nvIm="nvim" \
  nvIM="nvim" \
  nvMi="nvim" \
  nvMI="nvim" \
  nvmI="nvim" \
  nvIm="nvim" \
  nv="nvim" \
  nV="nvim" \
  nvi="nvim" \
  nvI="nvim" \
  vz="nvim $ZDOTDIR/.zshrc" \
  va="nvim $ZDOTDIR/aliasrc" \
  vp="nvim $ZDOTDIR/profile" \
  ve="nvim $ZDOTDIR/env" \
  vs="nvim $ZDOTDIR/shortcut" \
  vt="nvim $ZDOTDIR/script/ts" \
  vv="nvim ~/.config/nvim/init.vim" \
  vc="nvim ~/.vim/config/" \
  vvp="nvim ~/.config/nvim/plugins.vim"

# Directories
setopt autopushd pushdignoredups
alias \
  ..='cd ..' \
  ...='cd ../..' \
  ....='cd ../../..' \
  .....='cd ../../../..' \
  ......='cd ../../../../..' \
  mkd='mkdir -p'

vpmkd(){
  [ -z $1 ] && echo "Usage: vpmkd <name of plugin directory>, create a simple vim plugin structure" && return
  mkdir -p ~/.vim/pack/myplugins/start/$1/autoload ~/.vim/pack/myplugins/start/$1/plugin
  cd ~/.vim/pack/myplugins/start/$1
}

d() {
  [[ $1 == "-" ]] && cd - && return
  [ -z "$1" ] && dirs -v && return || cd +"$1"
}

# Tmux 
alias \
  tls="tmux ls" \
  tn="tmux new -t" \
  ta="tmux a -t" 

# cmd too long
alias \
  ez="restart_shell" \
  t="tree" \
  e="echo" \
  p="printf" \
  clr="clear" \
  mand="tldr" \
  wh="which" \
  x="xargs" \
  xov="xargs -o nvim" \
  xov="xargs -o nvim" \
  su="sudo -i" \
  del="trash" \
  mvdd="move_recent_download_to_dir"

# cmd too short, verbose output
alias \
  mv="mv -v" \
  cp="cp -v" \

ffn() {
  [ -z $* ] && echo "Usage ff: ff <regex | name of files>, find files matched regex in current directory" && return
  find . -type f -name "$*"
}

# git
alias \
  g="git" \
  ga="git add --all" \
  gm="git commit -m" \
  gp="git push" \
  gcl="git clone" \
  cgpush="config_git_push" \
  gb="git branch" \
  gna="git notes add" \
  gl="git log" \
  gd="git diff" \
  gsw="git switch"

gs(){
  [ -f nameList.txt ]  && echo "\nFound file nameList.txt\n" ; git status --untracked-files=no || git status
}


# gh repo create and push to repository
ghrc() {
  [ -z "$*" ] && echo "Please commit the change" && return
  git init
  gh repo create
  git add --all
  git commit -m "$*"
  git push --set-upstream origin main
}

# fedora package manager dnf
alias \
  dnfi="sudo dnf install" \
  dnfa="sudo dnf autoremove" \
  dnfs="dnf search"
 
# customized function
alias \
  qn="quick_note" \
  fnrs="file-name-remove-space" \

# Readalbe & color
alias \
  fd="fd --color never" \
  grep="grep -i --color=auto" \
  rg="rg -i" \
  htop="TERM=xterm-256color htop" \
  news="TERM=xterm-256color newsboat" \
  ll="ls -l --color=auto -h --group-directories-first" \
  la="ls -la --color=auto -h --group-directories-first" \
  mc="mc -b" \
  df="df -h"

# ls
l() {
  [ -z "$*" ] && ls -h --color=auto --group-directories-first && return
  command ls -h --color=auto --group-directories-first -"$1" "${@:2}"
}

# hugo
# list all create new hugo post and edit it
hugon() {
  cd ~/git_repo/mine/blog/
  tree -L 1 ~/git_repo/mine/blog/content/post
  [ -z $1 ] && echo "\nPlease provide name of post\n" && return
  mkdir -p ~/git_repo/mine/blog/content/post/$1
  hugo new post/$1/index.md
  nvim ~/git_repo/mine/blog/content/post/$1/index.md
}

hugos() {
  cd ~/git_repo/mine/blog/
  hugo server
}

# create executable temporary shell script
tmp() {
  touch tmp.sh && chmod +x tmp.sh && nvim tmp.sh
}

# kmoand
alias \
  k="start_kmonad" \
  kk="sudo kill kmonad" \
  kkk="sudo kill kmonad && start_kmonad"
