#!usr/bin/env bash

# keyboard shortcut
# fzf search directory name and change directory
#fzfcd(){
#  directory=$(fd --unrestricted --type directory | fzf)
#  [ -z $directory ] && return
#  cd $directory
#  ls -l --group-directories-first
#}

# shell mapping
bindkey -s '^f' 'fzfcd\n'
# paste using ctrl-v
_paste-copy-using-xsel() {
  LBUFFER+="$(xsel -b -o)"
}

zle -N _paste-copy-using-xsel
bindkey '^V' _paste-copy-using-xsel # Paste

bindkey -s '^z' 'fg\n'

bindkey -s '^k' '^[k'
